# coding: utf-8

"""
    CartoVista.Server.API.v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.grid_layer_update_parameters import GridLayerUpdateParameters  # noqa: E501
from swagger_client.rest import ApiException


class TestGridLayerUpdateParameters(unittest.TestCase):
    """GridLayerUpdateParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridLayerUpdateParameters(self):
        """Test GridLayerUpdateParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grid_layer_update_parameters.GridLayerUpdateParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
