# coding: utf-8

"""
    CartoVista.Server.API.v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.grid_layer_api import GridLayerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGridLayerApi(unittest.TestCase):
    """GridLayerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.grid_layer_api.GridLayerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_grid_layer_add_grid_source(self):
        """Test case for grid_layer_add_grid_source

        Add a grid source to an existing grid layer.  # noqa: E501
        """
        pass

    def test_grid_layer_create_grid_layer(self):
        """Test case for grid_layer_create_grid_layer

        Create a grid layer with the specified parameters.  # noqa: E501
        """
        pass

    def test_grid_layer_delete_grid_layer(self):
        """Test case for grid_layer_delete_grid_layer

        Delete an existing grid layer.  # noqa: E501
        """
        pass

    def test_grid_layer_delete_grid_source(self):
        """Test case for grid_layer_delete_grid_source

        Delete an existing grid source.  # noqa: E501
        """
        pass

    def test_grid_layer_get_data(self):
        """Test case for grid_layer_get_data

        """
        pass

    def test_grid_layer_get_grid_layer_by_id(self):
        """Test case for grid_layer_get_grid_layer_by_id

        Get a grid layer by identifier.  # noqa: E501
        """
        pass

    def test_grid_layer_get_grid_layers(self):
        """Test case for grid_layer_get_grid_layers

        Get the list of all grid layers.  # noqa: E501
        """
        pass

    def test_grid_layer_get_grid_source(self):
        """Test case for grid_layer_get_grid_source

        Get a grid source by identifier.  # noqa: E501
        """
        pass

    def test_grid_layer_get_grid_sources_for_grid_layer(self):
        """Test case for grid_layer_get_grid_sources_for_grid_layer

        Get all the grid sources associated with the grid layer.  # noqa: E501
        """
        pass

    def test_grid_layer_get_maps_by_grid_layer(self):
        """Test case for grid_layer_get_maps_by_grid_layer

        """
        pass

    def test_grid_layer_render(self):
        """Test case for grid_layer_render

        Generates a PNG of the grid source within the extent passed in the parameters and returns it as a byte array.  The inflection points are defined in `Styles` in the parameters.  # noqa: E501
        """
        pass

    def test_grid_layer_update_grid_layer(self):
        """Test case for grid_layer_update_grid_layer

        Update the properties of an existing grid layer.  # noqa: E501
        """
        pass

    def test_grid_layer_update_grid_source(self):
        """Test case for grid_layer_update_grid_source

        Update the properties of an existing grid source.  # noqa: E501
        """
        pass

    def test_grid_layer_update_grid_source_geotiff(self):
        """Test case for grid_layer_update_grid_source_geotiff

        Update the geoTIFF of an existing grid source.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
