# coding: utf-8

"""
    CartoVista.Server.API.v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.spatial_metadata_dto import SpatialMetadataDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestSpatialMetadataDTO(unittest.TestCase):
    """SpatialMetadataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpatialMetadataDTO(self):
        """Test SpatialMetadataDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.spatial_metadata_dto.SpatialMetadataDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
