# coding: utf-8

"""
    CartoVista.Server.API.v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.layer_api import LayerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLayerApi(unittest.TestCase):
    """LayerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.layer_api.LayerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_layer_create_layer(self):
        """Test case for layer_create_layer

        """
        pass

    def test_layer_create_layer_from_zip(self):
        """Test case for layer_create_layer_from_zip

        """
        pass

    def test_layer_delete_layer_by_id(self):
        """Test case for layer_delete_layer_by_id

        """
        pass

    def test_layer_get_layer_by_id(self):
        """Test case for layer_get_layer_by_id

        """
        pass

    def test_layer_get_layers(self):
        """Test case for layer_get_layers

        """
        pass

    def test_layer_set_data_column_unique_id(self):
        """Test case for layer_set_data_column_unique_id

        """
        pass

    def test_layer_set_unique_identifier(self):
        """Test case for layer_set_unique_identifier

        """
        pass

    def test_layer_update_layer(self):
        """Test case for layer_update_layer

        """
        pass

    def test_layer_update_layer_from_zip(self):
        """Test case for layer_update_layer_from_zip

        """
        pass


if __name__ == '__main__':
    unittest.main()
