/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApiCreateUpdateReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiCreateUpdateReportTests
    {
        // TODO uncomment below to declare an instance variable for ApiCreateUpdateReport
        //private ApiCreateUpdateReport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiCreateUpdateReport
            //instance = new ApiCreateUpdateReport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiCreateUpdateReport
        /// </summary>
        [Test]
        public void ApiCreateUpdateReportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiCreateUpdateReport
            //Assert.IsInstanceOfType<ApiCreateUpdateReport> (instance, "variable 'instance' is a ApiCreateUpdateReport");
        }


        /// <summary>
        /// Test the property 'UpdateCount'
        /// </summary>
        [Test]
        public void UpdateCountTest()
        {
            // TODO unit test for the property 'UpdateCount'
        }
        /// <summary>
        /// Test the property 'CreateCount'
        /// </summary>
        [Test]
        public void CreateCountTest()
        {
            // TODO unit test for the property 'CreateCount'
        }
        /// <summary>
        /// Test the property 'InsertedIdentifiers'
        /// </summary>
        [Test]
        public void InsertedIdentifiersTest()
        {
            // TODO unit test for the property 'InsertedIdentifiers'
        }
        /// <summary>
        /// Test the property 'UpdatedIdentifiers'
        /// </summary>
        [Test]
        public void UpdatedIdentifiersTest()
        {
            // TODO unit test for the property 'UpdatedIdentifiers'
        }
        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Test]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }

    }

}
