/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ApiDeleteReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiDeleteReportTests
    {
        // TODO uncomment below to declare an instance variable for ApiDeleteReport
        //private ApiDeleteReport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiDeleteReport
            //instance = new ApiDeleteReport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiDeleteReport
        /// </summary>
        [Test]
        public void ApiDeleteReportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiDeleteReport
            //Assert.IsInstanceOfType<ApiDeleteReport> (instance, "variable 'instance' is a ApiDeleteReport");
        }


        /// <summary>
        /// Test the property 'DeleteCount'
        /// </summary>
        [Test]
        public void DeleteCountTest()
        {
            // TODO unit test for the property 'DeleteCount'
        }
        /// <summary>
        /// Test the property 'DeletedIdentifiers'
        /// </summary>
        [Test]
        public void DeletedIdentifiersTest()
        {
            // TODO unit test for the property 'DeletedIdentifiers'
        }
        /// <summary>
        /// Test the property 'ErrorCount'
        /// </summary>
        [Test]
        public void ErrorCountTest()
        {
            // TODO unit test for the property 'ErrorCount'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }

    }

}
