/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeatureLongLatCreateParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureLongLatCreateParameterTests
    {
        // TODO uncomment below to declare an instance variable for FeatureLongLatCreateParameter
        //private FeatureLongLatCreateParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureLongLatCreateParameter
            //instance = new FeatureLongLatCreateParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureLongLatCreateParameter
        /// </summary>
        [Test]
        public void FeatureLongLatCreateParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeatureLongLatCreateParameter
            //Assert.IsInstanceOfType<FeatureLongLatCreateParameter> (instance, "variable 'instance' is a FeatureLongLatCreateParameter");
        }


        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'FeatureType'
        /// </summary>
        [Test]
        public void FeatureTypeTest()
        {
            // TODO unit test for the property 'FeatureType'
        }
        /// <summary>
        /// Test the property 'DataColumnsIdentifiers'
        /// </summary>
        [Test]
        public void DataColumnsIdentifiersTest()
        {
            // TODO unit test for the property 'DataColumnsIdentifiers'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Test]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
        /// <summary>
        /// Test the property 'Proj4'
        /// </summary>
        [Test]
        public void Proj4Test()
        {
            // TODO unit test for the property 'Proj4'
        }

    }

}
