/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FeatureWKTUpdateParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureWKTUpdateParameterTests
    {
        // TODO uncomment below to declare an instance variable for FeatureWKTUpdateParameter
        //private FeatureWKTUpdateParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureWKTUpdateParameter
            //instance = new FeatureWKTUpdateParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureWKTUpdateParameter
        /// </summary>
        [Test]
        public void FeatureWKTUpdateParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeatureWKTUpdateParameter
            //Assert.IsInstanceOfType<FeatureWKTUpdateParameter> (instance, "variable 'instance' is a FeatureWKTUpdateParameter");
        }


        /// <summary>
        /// Test the property 'WKT'
        /// </summary>
        [Test]
        public void WKTTest()
        {
            // TODO unit test for the property 'WKT'
        }
        /// <summary>
        /// Test the property 'FeatureType'
        /// </summary>
        [Test]
        public void FeatureTypeTest()
        {
            // TODO unit test for the property 'FeatureType'
        }
        /// <summary>
        /// Test the property 'Proj4'
        /// </summary>
        [Test]
        public void Proj4Test()
        {
            // TODO unit test for the property 'Proj4'
        }

    }

}
