/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MapDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MapDTOTests
    {
        // TODO uncomment below to declare an instance variable for MapDTO
        //private MapDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MapDTO
            //instance = new MapDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MapDTO
        /// </summary>
        [Test]
        public void MapDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MapDTO
            //Assert.IsInstanceOfType<MapDTO> (instance, "variable 'instance' is a MapDTO");
        }


        /// <summary>
        /// Test the property 'ConfigHTML5MapPathLocation'
        /// </summary>
        [Test]
        public void ConfigHTML5MapPathLocationTest()
        {
            // TODO unit test for the property 'ConfigHTML5MapPathLocation'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Test]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeDescription'
        /// </summary>
        [Test]
        public void TypeDescriptionTest()
        {
            // TODO unit test for the property 'TypeDescription'
        }
        /// <summary>
        /// Test the property 'SpatialMetaDataDTOs'
        /// </summary>
        [Test]
        public void SpatialMetaDataDTOsTest()
        {
            // TODO unit test for the property 'SpatialMetaDataDTOs'
        }
        /// <summary>
        /// Test the property 'PublicAccess'
        /// </summary>
        [Test]
        public void PublicAccessTest()
        {
            // TODO unit test for the property 'PublicAccess'
        }
        /// <summary>
        /// Test the property 'CustomViewer'
        /// </summary>
        [Test]
        public void CustomViewerTest()
        {
            // TODO unit test for the property 'CustomViewer'
        }
        /// <summary>
        /// Test the property 'OriginalMapPackageTimestamp'
        /// </summary>
        [Test]
        public void OriginalMapPackageTimestampTest()
        {
            // TODO unit test for the property 'OriginalMapPackageTimestamp'
        }
        /// <summary>
        /// Test the property 'IsMapTerritoryReady'
        /// </summary>
        [Test]
        public void IsMapTerritoryReadyTest()
        {
            // TODO unit test for the property 'IsMapTerritoryReady'
        }
        /// <summary>
        /// Test the property 'ThumbnailVersion'
        /// </summary>
        [Test]
        public void ThumbnailVersionTest()
        {
            // TODO unit test for the property 'ThumbnailVersion'
        }
        /// <summary>
        /// Test the property 'FolderId'
        /// </summary>
        [Test]
        public void FolderIdTest()
        {
            // TODO unit test for the property 'FolderId'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Editable'
        /// </summary>
        [Test]
        public void EditableTest()
        {
            // TODO unit test for the property 'Editable'
        }
        /// <summary>
        /// Test the property 'SeoTitle'
        /// </summary>
        [Test]
        public void SeoTitleTest()
        {
            // TODO unit test for the property 'SeoTitle'
        }
        /// <summary>
        /// Test the property 'SeoDescription'
        /// </summary>
        [Test]
        public void SeoDescriptionTest()
        {
            // TODO unit test for the property 'SeoDescription'
        }
        /// <summary>
        /// Test the property 'SeoCustomHTML'
        /// </summary>
        [Test]
        public void SeoCustomHTMLTest()
        {
            // TODO unit test for the property 'SeoCustomHTML'
        }
        /// <summary>
        /// Test the property 'ScoringEnabled'
        /// </summary>
        [Test]
        public void ScoringEnabledTest()
        {
            // TODO unit test for the property 'ScoringEnabled'
        }
        /// <summary>
        /// Test the property 'StoragePath'
        /// </summary>
        [Test]
        public void StoragePathTest()
        {
            // TODO unit test for the property 'StoragePath'
        }
        /// <summary>
        /// Test the property 'DynamicThumbnailURL'
        /// </summary>
        [Test]
        public void DynamicThumbnailURLTest()
        {
            // TODO unit test for the property 'DynamicThumbnailURL'
        }
        /// <summary>
        /// Test the property 'ModifiedThumbnail'
        /// </summary>
        [Test]
        public void ModifiedThumbnailTest()
        {
            // TODO unit test for the property 'ModifiedThumbnail'
        }
        /// <summary>
        /// Test the property 'MapUrl'
        /// </summary>
        [Test]
        public void MapUrlTest()
        {
            // TODO unit test for the property 'MapUrl'
        }
        /// <summary>
        /// Test the property 'LanguageDescription'
        /// </summary>
        [Test]
        public void LanguageDescriptionTest()
        {
            // TODO unit test for the property 'LanguageDescription'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Test]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedAuthor'
        /// </summary>
        [Test]
        public void LastModifiedAuthorTest()
        {
            // TODO unit test for the property 'LastModifiedAuthor'
        }
        /// <summary>
        /// Test the property 'LastModifiedTime'
        /// </summary>
        [Test]
        public void LastModifiedTimeTest()
        {
            // TODO unit test for the property 'LastModifiedTime'
        }
        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Test]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }
        /// <summary>
        /// Test the property 'OwnerName'
        /// </summary>
        [Test]
        public void OwnerNameTest()
        {
            // TODO unit test for the property 'OwnerName'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }
        /// <summary>
        /// Test the property 'CurrentUserHasModifyPermission'
        /// </summary>
        [Test]
        public void CurrentUserHasModifyPermissionTest()
        {
            // TODO unit test for the property 'CurrentUserHasModifyPermission'
        }
        /// <summary>
        /// Test the property 'RepresentationUseCount'
        /// </summary>
        [Test]
        public void RepresentationUseCountTest()
        {
            // TODO unit test for the property 'RepresentationUseCount'
        }
        /// <summary>
        /// Test the property 'WebApplicationPath'
        /// </summary>
        [Test]
        public void WebApplicationPathTest()
        {
            // TODO unit test for the property 'WebApplicationPath'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
