/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RouteSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RouteSummaryTests
    {
        // TODO uncomment below to declare an instance variable for RouteSummary
        //private RouteSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RouteSummary
            //instance = new RouteSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RouteSummary
        /// </summary>
        [Test]
        public void RouteSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RouteSummary
            //Assert.IsInstanceOfType<RouteSummary> (instance, "variable 'instance' is a RouteSummary");
        }


        /// <summary>
        /// Test the property 'OriginLatitude'
        /// </summary>
        [Test]
        public void OriginLatitudeTest()
        {
            // TODO unit test for the property 'OriginLatitude'
        }
        /// <summary>
        /// Test the property 'OriginLongitude'
        /// </summary>
        [Test]
        public void OriginLongitudeTest()
        {
            // TODO unit test for the property 'OriginLongitude'
        }
        /// <summary>
        /// Test the property 'DestinationLatitude'
        /// </summary>
        [Test]
        public void DestinationLatitudeTest()
        {
            // TODO unit test for the property 'DestinationLatitude'
        }
        /// <summary>
        /// Test the property 'DestinationLongitude'
        /// </summary>
        [Test]
        public void DestinationLongitudeTest()
        {
            // TODO unit test for the property 'DestinationLongitude'
        }
        /// <summary>
        /// Test the property 'DriveDistanceMeters'
        /// </summary>
        [Test]
        public void DriveDistanceMetersTest()
        {
            // TODO unit test for the property 'DriveDistanceMeters'
        }
        /// <summary>
        /// Test the property 'DriveTimeMinutes'
        /// </summary>
        [Test]
        public void DriveTimeMinutesTest()
        {
            // TODO unit test for the property 'DriveTimeMinutes'
        }
        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Test]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }

    }

}
