# coding: utf-8

"""
    CartoVista.Server.API.v1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiCreateUpdateReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'update_count': 'int',
        'create_count': 'int',
        'inserted_identifiers': 'list[str]',
        'updated_identifiers': 'list[str]',
        'error_count': 'int',
        'error_details': 'list[ErrorDetail]'
    }

    attribute_map = {
        'update_count': 'UpdateCount',
        'create_count': 'CreateCount',
        'inserted_identifiers': 'InsertedIdentifiers',
        'updated_identifiers': 'UpdatedIdentifiers',
        'error_count': 'ErrorCount',
        'error_details': 'ErrorDetails'
    }

    def __init__(self, update_count=None, create_count=None, inserted_identifiers=None, updated_identifiers=None, error_count=None, error_details=None):  # noqa: E501
        """ApiCreateUpdateReport - a model defined in Swagger"""  # noqa: E501

        self._update_count = None
        self._create_count = None
        self._inserted_identifiers = None
        self._updated_identifiers = None
        self._error_count = None
        self._error_details = None
        self.discriminator = None

        if update_count is not None:
            self.update_count = update_count
        if create_count is not None:
            self.create_count = create_count
        if inserted_identifiers is not None:
            self.inserted_identifiers = inserted_identifiers
        if updated_identifiers is not None:
            self.updated_identifiers = updated_identifiers
        if error_count is not None:
            self.error_count = error_count
        if error_details is not None:
            self.error_details = error_details

    @property
    def update_count(self):
        """Gets the update_count of this ApiCreateUpdateReport.  # noqa: E501


        :return: The update_count of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: int
        """
        return self._update_count

    @update_count.setter
    def update_count(self, update_count):
        """Sets the update_count of this ApiCreateUpdateReport.


        :param update_count: The update_count of this ApiCreateUpdateReport.  # noqa: E501
        :type: int
        """

        self._update_count = update_count

    @property
    def create_count(self):
        """Gets the create_count of this ApiCreateUpdateReport.  # noqa: E501


        :return: The create_count of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: int
        """
        return self._create_count

    @create_count.setter
    def create_count(self, create_count):
        """Sets the create_count of this ApiCreateUpdateReport.


        :param create_count: The create_count of this ApiCreateUpdateReport.  # noqa: E501
        :type: int
        """

        self._create_count = create_count

    @property
    def inserted_identifiers(self):
        """Gets the inserted_identifiers of this ApiCreateUpdateReport.  # noqa: E501


        :return: The inserted_identifiers of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: list[str]
        """
        return self._inserted_identifiers

    @inserted_identifiers.setter
    def inserted_identifiers(self, inserted_identifiers):
        """Sets the inserted_identifiers of this ApiCreateUpdateReport.


        :param inserted_identifiers: The inserted_identifiers of this ApiCreateUpdateReport.  # noqa: E501
        :type: list[str]
        """

        self._inserted_identifiers = inserted_identifiers

    @property
    def updated_identifiers(self):
        """Gets the updated_identifiers of this ApiCreateUpdateReport.  # noqa: E501


        :return: The updated_identifiers of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: list[str]
        """
        return self._updated_identifiers

    @updated_identifiers.setter
    def updated_identifiers(self, updated_identifiers):
        """Sets the updated_identifiers of this ApiCreateUpdateReport.


        :param updated_identifiers: The updated_identifiers of this ApiCreateUpdateReport.  # noqa: E501
        :type: list[str]
        """

        self._updated_identifiers = updated_identifiers

    @property
    def error_count(self):
        """Gets the error_count of this ApiCreateUpdateReport.  # noqa: E501


        :return: The error_count of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: int
        """
        return self._error_count

    @error_count.setter
    def error_count(self, error_count):
        """Sets the error_count of this ApiCreateUpdateReport.


        :param error_count: The error_count of this ApiCreateUpdateReport.  # noqa: E501
        :type: int
        """

        self._error_count = error_count

    @property
    def error_details(self):
        """Gets the error_details of this ApiCreateUpdateReport.  # noqa: E501


        :return: The error_details of this ApiCreateUpdateReport.  # noqa: E501
        :rtype: list[ErrorDetail]
        """
        return self._error_details

    @error_details.setter
    def error_details(self, error_details):
        """Sets the error_details of this ApiCreateUpdateReport.


        :param error_details: The error_details of this ApiCreateUpdateReport.  # noqa: E501
        :type: list[ErrorDetail]
        """

        self._error_details = error_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiCreateUpdateReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiCreateUpdateReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
