/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CartoVistaserverapiv1) {
      root.CartoVistaserverapiv1 = {};
    }
    root.CartoVistaserverapiv1.DataTableCreateParameter = factory(root.CartoVistaserverapiv1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DataTableCreateParameter model module.
   * @module model/DataTableCreateParameter
   * @version v1
   */

  /**
   * Constructs a new <code>DataTableCreateParameter</code>.
   * @alias module:model/DataTableCreateParameter
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DataTableCreateParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataTableCreateParameter} obj Optional instance to populate.
   * @return {module:model/DataTableCreateParameter} The populated <code>DataTableCreateParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Identifier'))
        obj.identifier = ApiClient.convertToType(data['Identifier'], 'String');
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('Metadata'))
        obj.metadata = ApiClient.convertToType(data['Metadata'], 'String');
      if (data.hasOwnProperty('Description'))
        obj.description = ApiClient.convertToType(data['Description'], 'String');
      if (data.hasOwnProperty('SystemIdentifier'))
        obj.systemIdentifier = ApiClient.convertToType(data['SystemIdentifier'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} identifier
   */
  exports.prototype.identifier = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} metadata
   */
  exports.prototype.metadata = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} systemIdentifier
   */
  exports.prototype.systemIdentifier = undefined;

  return exports;

}));
