/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CartoVistaserverapiv1) {
      root.CartoVistaserverapiv1 = {};
    }
    root.CartoVistaserverapiv1.GridSourceRenderStyleParameter = factory(root.CartoVistaserverapiv1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GridSourceRenderStyleParameter model module.
   * @module model/GridSourceRenderStyleParameter
   * @version v1
   */

  /**
   * Constructs a new <code>GridSourceRenderStyleParameter</code>.
   * @alias module:model/GridSourceRenderStyleParameter
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GridSourceRenderStyleParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GridSourceRenderStyleParameter} obj Optional instance to populate.
   * @return {module:model/GridSourceRenderStyleParameter} The populated <code>GridSourceRenderStyleParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('min'))
        obj.min = ApiClient.convertToType(data['min'], 'Number');
      if (data.hasOwnProperty('max'))
        obj.max = ApiClient.convertToType(data['max'], 'Number');
      if (data.hasOwnProperty('color'))
        obj.color = ApiClient.convertToType(data['color'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} value
   */
  exports.prototype.value = undefined;

  /**
   * @member {Number} min
   */
  exports.prototype.min = undefined;

  /**
   * @member {Number} max
   */
  exports.prototype.max = undefined;

  /**
   * @member {String} color
   */
  exports.prototype.color = undefined;

  return exports;

}));
