/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CartoVistaserverapiv1) {
      root.CartoVistaserverapiv1 = {};
    }
    root.CartoVistaserverapiv1.Isochrone = factory(root.CartoVistaserverapiv1.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Isochrone model module.
   * @module model/Isochrone
   * @version v1
   */

  /**
   * Constructs a new <code>Isochrone</code>.
   * @alias module:model/Isochrone
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Isochrone</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Isochrone} obj Optional instance to populate.
   * @return {module:model/Isochrone} The populated <code>Isochrone</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Longitude'))
        obj.longitude = ApiClient.convertToType(data['Longitude'], 'Number');
      if (data.hasOwnProperty('Latitude'))
        obj.latitude = ApiClient.convertToType(data['Latitude'], 'Number');
      if (data.hasOwnProperty('Range'))
        obj.range = ApiClient.convertToType(data['Range'], 'String');
      if (data.hasOwnProperty('RangeType'))
        obj.rangeType = ApiClient.convertToType(data['RangeType'], 'String');
      if (data.hasOwnProperty('Mode'))
        obj.mode = ApiClient.convertToType(data['Mode'], 'String');
      if (data.hasOwnProperty('DepartureTime'))
        obj.departureTime = ApiClient.convertToType(data['DepartureTime'], 'String');
      if (data.hasOwnProperty('IsolineCoordinates'))
        obj.isolineCoordinates = ApiClient.convertToType(data['IsolineCoordinates'], ['Number']);
    }
    return obj;
  }

  /**
   * @member {Number} longitude
   */
  exports.prototype.longitude = undefined;

  /**
   * @member {Number} latitude
   */
  exports.prototype.latitude = undefined;

  /**
   * @member {String} range
   */
  exports.prototype.range = undefined;

  /**
   * @member {String} rangeType
   */
  exports.prototype.rangeType = undefined;

  /**
   * @member {String} mode
   */
  exports.prototype.mode = undefined;

  /**
   * @member {String} departureTime
   */
  exports.prototype.departureTime = undefined;

  /**
   * @member {Array.<Number>} isolineCoordinates
   */
  exports.prototype.isolineCoordinates = undefined;

  return exports;

}));
