/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CartoVistaserverapiv1);
  }
}(this, function(expect, CartoVistaserverapiv1) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ApiInsertReport', function() {
      beforeEach(function() {
        instance = new CartoVistaserverapiv1.ApiInsertReport();
      });

      it('should create an instance of ApiInsertReport', function() {
        // TODO: update the code to test ApiInsertReport
        expect(instance).to.be.a(CartoVistaserverapiv1.ApiInsertReport);
      });

      it('should have the property createCount (base name: "CreateCount")', function() {
        // TODO: update the code to test the property createCount
        expect(instance).to.have.property('createCount');
        // expect(instance.createCount).to.be(expectedValueLiteral);
      });

      it('should have the property insertedIdentifiers (base name: "InsertedIdentifiers")', function() {
        // TODO: update the code to test the property insertedIdentifiers
        expect(instance).to.have.property('insertedIdentifiers');
        // expect(instance.insertedIdentifiers).to.be(expectedValueLiteral);
      });

      it('should have the property updatedIdentifiers (base name: "UpdatedIdentifiers")', function() {
        // TODO: update the code to test the property updatedIdentifiers
        expect(instance).to.have.property('updatedIdentifiers');
        // expect(instance.updatedIdentifiers).to.be(expectedValueLiteral);
      });

      it('should have the property errorCount (base name: "ErrorCount")', function() {
        // TODO: update the code to test the property errorCount
        expect(instance).to.have.property('errorCount');
        // expect(instance.errorCount).to.be(expectedValueLiteral);
      });

      it('should have the property errorDetails (base name: "ErrorDetails")', function() {
        // TODO: update the code to test the property errorDetails
        expect(instance).to.have.property('errorDetails');
        // expect(instance.errorDetails).to.be(expectedValueLiteral);
      });

    });
  });

}));
