/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CartoVistaserverapiv1);
  }
}(this, function(expect, CartoVistaserverapiv1) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GridSourceUpdateParameters', function() {
      beforeEach(function() {
        instance = new CartoVistaserverapiv1.GridSourceUpdateParameters();
      });

      it('should create an instance of GridSourceUpdateParameters', function() {
        // TODO: update the code to test GridSourceUpdateParameters
        expect(instance).to.be.a(CartoVistaserverapiv1.GridSourceUpdateParameters);
      });

      it('should have the property uniqueIdentifier (base name: "uniqueIdentifier")', function() {
        // TODO: update the code to test the property uniqueIdentifier
        expect(instance).to.have.property('uniqueIdentifier');
        // expect(instance.uniqueIdentifier).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property noDataEnabled (base name: "noDataEnabled")', function() {
        // TODO: update the code to test the property noDataEnabled
        expect(instance).to.have.property('noDataEnabled');
        // expect(instance.noDataEnabled).to.be(expectedValueLiteral);
      });

      it('should have the property noDataValue (base name: "noDataValue")', function() {
        // TODO: update the code to test the property noDataValue
        expect(instance).to.have.property('noDataValue');
        // expect(instance.noDataValue).to.be(expectedValueLiteral);
      });

    });
  });

}));
