/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CartoVistaserverapiv1);
  }
}(this, function(expect, CartoVistaserverapiv1) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LayerCreateParameter', function() {
      beforeEach(function() {
        instance = new CartoVistaserverapiv1.LayerCreateParameter();
      });

      it('should create an instance of LayerCreateParameter', function() {
        // TODO: update the code to test LayerCreateParameter
        expect(instance).to.be.a(CartoVistaserverapiv1.LayerCreateParameter);
      });

      it('should have the property identifier (base name: "Identifier")', function() {
        // TODO: update the code to test the property identifier
        expect(instance).to.have.property('identifier');
        // expect(instance.identifier).to.be(expectedValueLiteral);
      });

      it('should have the property proj4 (base name: "Proj4")', function() {
        // TODO: update the code to test the property proj4
        expect(instance).to.have.property('proj4');
        // expect(instance.proj4).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "Name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property metadata (base name: "Metadata")', function() {
        // TODO: update the code to test the property metadata
        expect(instance).to.have.property('metadata');
        // expect(instance.metadata).to.be(expectedValueLiteral);
      });

      it('should have the property geometryType (base name: "GeometryType")', function() {
        // TODO: update the code to test the property geometryType
        expect(instance).to.have.property('geometryType');
        // expect(instance.geometryType).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "Description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property vectorTiling (base name: "VectorTiling")', function() {
        // TODO: update the code to test the property vectorTiling
        expect(instance).to.have.property('vectorTiling');
        // expect(instance.vectorTiling).to.be(expectedValueLiteral);
      });

      it('should have the property systemIdentifier (base name: "SystemIdentifier")', function() {
        // TODO: update the code to test the property systemIdentifier
        expect(instance).to.have.property('systemIdentifier');
        // expect(instance.systemIdentifier).to.be(expectedValueLiteral);
      });

      it('should have the property dataTableSystemIdentifier (base name: "DataTableSystemIdentifier")', function() {
        // TODO: update the code to test the property dataTableSystemIdentifier
        expect(instance).to.have.property('dataTableSystemIdentifier');
        // expect(instance.dataTableSystemIdentifier).to.be(expectedValueLiteral);
      });

      it('should have the property featureIdColumnSystemIdentifier (base name: "FeatureIdColumnSystemIdentifier")', function() {
        // TODO: update the code to test the property featureIdColumnSystemIdentifier
        expect(instance).to.have.property('featureIdColumnSystemIdentifier');
        // expect(instance.featureIdColumnSystemIdentifier).to.be(expectedValueLiteral);
      });

    });
  });

}));
