/*
 * CartoVista.Server.API.v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CartoVistaserverapiv1);
  }
}(this, function(expect, CartoVistaserverapiv1) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Map', function() {
      beforeEach(function() {
        instance = new CartoVistaserverapiv1.Map();
      });

      it('should create an instance of Map', function() {
        // TODO: update the code to test Map
        expect(instance).to.be.a(CartoVistaserverapiv1.Map);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property uniqueIdentifier (base name: "uniqueIdentifier")', function() {
        // TODO: update the code to test the property uniqueIdentifier
        expect(instance).to.have.property('uniqueIdentifier');
        // expect(instance.uniqueIdentifier).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property isMapTerritoryReady (base name: "isMapTerritoryReady")', function() {
        // TODO: update the code to test the property isMapTerritoryReady
        expect(instance).to.have.property('isMapTerritoryReady');
        // expect(instance.isMapTerritoryReady).to.be(expectedValueLiteral);
      });

      it('should have the property editable (base name: "editable")', function() {
        // TODO: update the code to test the property editable
        expect(instance).to.have.property('editable');
        // expect(instance.editable).to.be(expectedValueLiteral);
      });

      it('should have the property seoTitle (base name: "seoTitle")', function() {
        // TODO: update the code to test the property seoTitle
        expect(instance).to.have.property('seoTitle');
        // expect(instance.seoTitle).to.be(expectedValueLiteral);
      });

      it('should have the property seoDescription (base name: "seoDescription")', function() {
        // TODO: update the code to test the property seoDescription
        expect(instance).to.have.property('seoDescription');
        // expect(instance.seoDescription).to.be(expectedValueLiteral);
      });

      it('should have the property seoCustomHTML (base name: "seoCustomHTML")', function() {
        // TODO: update the code to test the property seoCustomHTML
        expect(instance).to.have.property('seoCustomHTML');
        // expect(instance.seoCustomHTML).to.be(expectedValueLiteral);
      });

      it('should have the property scoringEnabled (base name: "scoringEnabled")', function() {
        // TODO: update the code to test the property scoringEnabled
        expect(instance).to.have.property('scoringEnabled');
        // expect(instance.scoringEnabled).to.be(expectedValueLiteral);
      });

    });
  });

}));
