/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// LayerUpdateParameter
    /// </summary>
    [DataContract]
    public partial class LayerUpdateParameter :  IEquatable<LayerUpdateParameter>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LayerUpdateParameter" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="description">description.</param>
        /// <param name="vectorTiling">vectorTiling.</param>
        /// <param name="dataColumns">dataColumns.</param>
        public LayerUpdateParameter(string name = default(string), string metadata = default(string), string description = default(string), bool? vectorTiling = default(bool?), List<DataColumnUpdateParameterExtended> dataColumns = default(List<DataColumnUpdateParameterExtended>))
        {
            this.Name = name;
            this.Metadata = metadata;
            this.Description = description;
            this.VectorTiling = vectorTiling;
            this.DataColumns = dataColumns;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name="Metadata", EmitDefaultValue=false)]
        public string Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets VectorTiling
        /// </summary>
        [DataMember(Name="VectorTiling", EmitDefaultValue=false)]
        public bool? VectorTiling { get; set; }

        /// <summary>
        /// Gets or Sets DataColumns
        /// </summary>
        [DataMember(Name="DataColumns", EmitDefaultValue=false)]
        public List<DataColumnUpdateParameterExtended> DataColumns { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LayerUpdateParameter {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  VectorTiling: ").Append(VectorTiling).Append("\n");
            sb.Append("  DataColumns: ").Append(DataColumns).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LayerUpdateParameter);
        }

        /// <summary>
        /// Returns true if LayerUpdateParameter instances are equal
        /// </summary>
        /// <param name="input">Instance of LayerUpdateParameter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LayerUpdateParameter input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.VectorTiling == input.VectorTiling ||
                    (this.VectorTiling != null &&
                    this.VectorTiling.Equals(input.VectorTiling))
                ) && 
                (
                    this.DataColumns == input.DataColumns ||
                    this.DataColumns != null &&
                    this.DataColumns.SequenceEqual(input.DataColumns)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.VectorTiling != null)
                    hashCode = hashCode * 59 + this.VectorTiling.GetHashCode();
                if (this.DataColumns != null)
                    hashCode = hashCode * 59 + this.DataColumns.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
