/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Layer
    /// </summary>
    [DataContract]
    public partial class Layer :  IEquatable<Layer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Layer" /> class.
        /// </summary>
        /// <param name="uniqueIdentifier">uniqueIdentifier.</param>
        /// <param name="creationTime">creationTime.</param>
        /// <param name="dataTableUniqueIdentifier">dataTableUniqueIdentifier.</param>
        /// <param name="description">description.</param>
        /// <param name="geometryType">geometryType.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="modifiedTime">modifiedTime.</param>
        /// <param name="name">name.</param>
        /// <param name="proj4">proj4.</param>
        /// <param name="rowCount">rowCount.</param>
        /// <param name="systemIdentifier">systemIdentifier.</param>
        /// <param name="uniqueIdDataColumn">uniqueIdDataColumn.</param>
        public Layer(string uniqueIdentifier = default(string), string creationTime = default(string), string dataTableUniqueIdentifier = default(string), string description = default(string), string geometryType = default(string), string metadata = default(string), string modifiedTime = default(string), string name = default(string), string proj4 = default(string), int? rowCount = default(int?), Guid? systemIdentifier = default(Guid?), Guid? uniqueIdDataColumn = default(Guid?))
        {
            this.UniqueIdentifier = uniqueIdentifier;
            this.CreationTime = creationTime;
            this.DataTableUniqueIdentifier = dataTableUniqueIdentifier;
            this.Description = description;
            this.GeometryType = geometryType;
            this.Metadata = metadata;
            this.ModifiedTime = modifiedTime;
            this.Name = name;
            this.Proj4 = proj4;
            this.RowCount = rowCount;
            this.SystemIdentifier = systemIdentifier;
            this.UniqueIdDataColumn = uniqueIdDataColumn;
        }
        
        /// <summary>
        /// Gets or Sets UniqueIdentifier
        /// </summary>
        [DataMember(Name="UniqueIdentifier", EmitDefaultValue=false)]
        public string UniqueIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets CreationTime
        /// </summary>
        [DataMember(Name="CreationTime", EmitDefaultValue=false)]
        public string CreationTime { get; set; }

        /// <summary>
        /// Gets or Sets DataTableUniqueIdentifier
        /// </summary>
        [DataMember(Name="DataTableUniqueIdentifier", EmitDefaultValue=false)]
        public string DataTableUniqueIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets GeometryType
        /// </summary>
        [DataMember(Name="GeometryType", EmitDefaultValue=false)]
        public string GeometryType { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name="Metadata", EmitDefaultValue=false)]
        public string Metadata { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedTime
        /// </summary>
        [DataMember(Name="ModifiedTime", EmitDefaultValue=false)]
        public string ModifiedTime { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Proj4
        /// </summary>
        [DataMember(Name="Proj4", EmitDefaultValue=false)]
        public string Proj4 { get; set; }

        /// <summary>
        /// Gets or Sets RowCount
        /// </summary>
        [DataMember(Name="RowCount", EmitDefaultValue=false)]
        public int? RowCount { get; set; }

        /// <summary>
        /// Gets or Sets SystemIdentifier
        /// </summary>
        [DataMember(Name="SystemIdentifier", EmitDefaultValue=false)]
        public Guid? SystemIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets UniqueIdDataColumn
        /// </summary>
        [DataMember(Name="UniqueIdDataColumn", EmitDefaultValue=false)]
        public Guid? UniqueIdDataColumn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Layer {\n");
            sb.Append("  UniqueIdentifier: ").Append(UniqueIdentifier).Append("\n");
            sb.Append("  CreationTime: ").Append(CreationTime).Append("\n");
            sb.Append("  DataTableUniqueIdentifier: ").Append(DataTableUniqueIdentifier).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  GeometryType: ").Append(GeometryType).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  ModifiedTime: ").Append(ModifiedTime).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Proj4: ").Append(Proj4).Append("\n");
            sb.Append("  RowCount: ").Append(RowCount).Append("\n");
            sb.Append("  SystemIdentifier: ").Append(SystemIdentifier).Append("\n");
            sb.Append("  UniqueIdDataColumn: ").Append(UniqueIdDataColumn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Layer);
        }

        /// <summary>
        /// Returns true if Layer instances are equal
        /// </summary>
        /// <param name="input">Instance of Layer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Layer input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UniqueIdentifier == input.UniqueIdentifier ||
                    (this.UniqueIdentifier != null &&
                    this.UniqueIdentifier.Equals(input.UniqueIdentifier))
                ) && 
                (
                    this.CreationTime == input.CreationTime ||
                    (this.CreationTime != null &&
                    this.CreationTime.Equals(input.CreationTime))
                ) && 
                (
                    this.DataTableUniqueIdentifier == input.DataTableUniqueIdentifier ||
                    (this.DataTableUniqueIdentifier != null &&
                    this.DataTableUniqueIdentifier.Equals(input.DataTableUniqueIdentifier))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.GeometryType == input.GeometryType ||
                    (this.GeometryType != null &&
                    this.GeometryType.Equals(input.GeometryType))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                ) && 
                (
                    this.ModifiedTime == input.ModifiedTime ||
                    (this.ModifiedTime != null &&
                    this.ModifiedTime.Equals(input.ModifiedTime))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Proj4 == input.Proj4 ||
                    (this.Proj4 != null &&
                    this.Proj4.Equals(input.Proj4))
                ) && 
                (
                    this.RowCount == input.RowCount ||
                    (this.RowCount != null &&
                    this.RowCount.Equals(input.RowCount))
                ) && 
                (
                    this.SystemIdentifier == input.SystemIdentifier ||
                    (this.SystemIdentifier != null &&
                    this.SystemIdentifier.Equals(input.SystemIdentifier))
                ) && 
                (
                    this.UniqueIdDataColumn == input.UniqueIdDataColumn ||
                    (this.UniqueIdDataColumn != null &&
                    this.UniqueIdDataColumn.Equals(input.UniqueIdDataColumn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UniqueIdentifier != null)
                    hashCode = hashCode * 59 + this.UniqueIdentifier.GetHashCode();
                if (this.CreationTime != null)
                    hashCode = hashCode * 59 + this.CreationTime.GetHashCode();
                if (this.DataTableUniqueIdentifier != null)
                    hashCode = hashCode * 59 + this.DataTableUniqueIdentifier.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.GeometryType != null)
                    hashCode = hashCode * 59 + this.GeometryType.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.ModifiedTime != null)
                    hashCode = hashCode * 59 + this.ModifiedTime.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Proj4 != null)
                    hashCode = hashCode * 59 + this.Proj4.GetHashCode();
                if (this.RowCount != null)
                    hashCode = hashCode * 59 + this.RowCount.GetHashCode();
                if (this.SystemIdentifier != null)
                    hashCode = hashCode * 59 + this.SystemIdentifier.GetHashCode();
                if (this.UniqueIdDataColumn != null)
                    hashCode = hashCode * 59 + this.UniqueIdDataColumn.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
