/* 
 * CartoVista.Server.API.v1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RouteSummary
    /// </summary>
    [DataContract]
    public partial class RouteSummary :  IEquatable<RouteSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteSummary" /> class.
        /// </summary>
        /// <param name="originLatitude">originLatitude.</param>
        /// <param name="originLongitude">originLongitude.</param>
        /// <param name="destinationLatitude">destinationLatitude.</param>
        /// <param name="destinationLongitude">destinationLongitude.</param>
        /// <param name="driveDistanceMeters">driveDistanceMeters.</param>
        /// <param name="driveTimeMinutes">driveTimeMinutes.</param>
        /// <param name="coordinates">coordinates.</param>
        public RouteSummary(double? originLatitude = default(double?), double? originLongitude = default(double?), double? destinationLatitude = default(double?), double? destinationLongitude = default(double?), int? driveDistanceMeters = default(int?), int? driveTimeMinutes = default(int?), List<double?> coordinates = default(List<double?>))
        {
            this.OriginLatitude = originLatitude;
            this.OriginLongitude = originLongitude;
            this.DestinationLatitude = destinationLatitude;
            this.DestinationLongitude = destinationLongitude;
            this.DriveDistanceMeters = driveDistanceMeters;
            this.DriveTimeMinutes = driveTimeMinutes;
            this.Coordinates = coordinates;
        }
        
        /// <summary>
        /// Gets or Sets OriginLatitude
        /// </summary>
        [DataMember(Name="OriginLatitude", EmitDefaultValue=false)]
        public double? OriginLatitude { get; set; }

        /// <summary>
        /// Gets or Sets OriginLongitude
        /// </summary>
        [DataMember(Name="OriginLongitude", EmitDefaultValue=false)]
        public double? OriginLongitude { get; set; }

        /// <summary>
        /// Gets or Sets DestinationLatitude
        /// </summary>
        [DataMember(Name="DestinationLatitude", EmitDefaultValue=false)]
        public double? DestinationLatitude { get; set; }

        /// <summary>
        /// Gets or Sets DestinationLongitude
        /// </summary>
        [DataMember(Name="DestinationLongitude", EmitDefaultValue=false)]
        public double? DestinationLongitude { get; set; }

        /// <summary>
        /// Gets or Sets DriveDistanceMeters
        /// </summary>
        [DataMember(Name="DriveDistanceMeters", EmitDefaultValue=false)]
        public int? DriveDistanceMeters { get; set; }

        /// <summary>
        /// Gets or Sets DriveTimeMinutes
        /// </summary>
        [DataMember(Name="DriveTimeMinutes", EmitDefaultValue=false)]
        public int? DriveTimeMinutes { get; set; }

        /// <summary>
        /// Gets or Sets Coordinates
        /// </summary>
        [DataMember(Name="Coordinates", EmitDefaultValue=false)]
        public List<double?> Coordinates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RouteSummary {\n");
            sb.Append("  OriginLatitude: ").Append(OriginLatitude).Append("\n");
            sb.Append("  OriginLongitude: ").Append(OriginLongitude).Append("\n");
            sb.Append("  DestinationLatitude: ").Append(DestinationLatitude).Append("\n");
            sb.Append("  DestinationLongitude: ").Append(DestinationLongitude).Append("\n");
            sb.Append("  DriveDistanceMeters: ").Append(DriveDistanceMeters).Append("\n");
            sb.Append("  DriveTimeMinutes: ").Append(DriveTimeMinutes).Append("\n");
            sb.Append("  Coordinates: ").Append(Coordinates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RouteSummary);
        }

        /// <summary>
        /// Returns true if RouteSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of RouteSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RouteSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OriginLatitude == input.OriginLatitude ||
                    (this.OriginLatitude != null &&
                    this.OriginLatitude.Equals(input.OriginLatitude))
                ) && 
                (
                    this.OriginLongitude == input.OriginLongitude ||
                    (this.OriginLongitude != null &&
                    this.OriginLongitude.Equals(input.OriginLongitude))
                ) && 
                (
                    this.DestinationLatitude == input.DestinationLatitude ||
                    (this.DestinationLatitude != null &&
                    this.DestinationLatitude.Equals(input.DestinationLatitude))
                ) && 
                (
                    this.DestinationLongitude == input.DestinationLongitude ||
                    (this.DestinationLongitude != null &&
                    this.DestinationLongitude.Equals(input.DestinationLongitude))
                ) && 
                (
                    this.DriveDistanceMeters == input.DriveDistanceMeters ||
                    (this.DriveDistanceMeters != null &&
                    this.DriveDistanceMeters.Equals(input.DriveDistanceMeters))
                ) && 
                (
                    this.DriveTimeMinutes == input.DriveTimeMinutes ||
                    (this.DriveTimeMinutes != null &&
                    this.DriveTimeMinutes.Equals(input.DriveTimeMinutes))
                ) && 
                (
                    this.Coordinates == input.Coordinates ||
                    this.Coordinates != null &&
                    this.Coordinates.SequenceEqual(input.Coordinates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OriginLatitude != null)
                    hashCode = hashCode * 59 + this.OriginLatitude.GetHashCode();
                if (this.OriginLongitude != null)
                    hashCode = hashCode * 59 + this.OriginLongitude.GetHashCode();
                if (this.DestinationLatitude != null)
                    hashCode = hashCode * 59 + this.DestinationLatitude.GetHashCode();
                if (this.DestinationLongitude != null)
                    hashCode = hashCode * 59 + this.DestinationLongitude.GetHashCode();
                if (this.DriveDistanceMeters != null)
                    hashCode = hashCode * 59 + this.DriveDistanceMeters.GetHashCode();
                if (this.DriveTimeMinutes != null)
                    hashCode = hashCode * 59 + this.DriveTimeMinutes.GetHashCode();
                if (this.Coordinates != null)
                    hashCode = hashCode * 59 + this.Coordinates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
